version: '3.8'

services:
  plex-suggestions:
    build: .
    container_name: plex-suggestions
    environment:
      # Plex Configuration
      - PLEX_IP=${PLEX_IP}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - PLEX_SECTION_KEY=${PLEX_SECTION_KEY}
      
      # Radarr Configuration
      - RADARR_URL=${RADARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - RADARR_QUALITY_PROFILE=${RADARR_QUALITY_PROFILE}
      
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Run Configuration
      - RUN_INTERVAL_DAYS=${RUN_INTERVAL_DAYS:-0}
    
    env_file:
      - .env
    
    # Optional: Mount a volume for logs
    volumes:
      - ./logs:/app/logs
    
    # Restart policy based on RUN_INTERVAL_DAYS
    # If RUN_INTERVAL_DAYS > 0, restart on failure
    # If RUN_INTERVAL_DAYS = 0, don't restart (run once)
    restart: ${RESTART_POLICY:-no}